### ISSUE TITLE
Make title of folders unfold as well.

### ISSUE THREAD

**Issue by DeniseSl22** [ammar257ammar/snorql-extended#1]
Hi @ammar257ammar ; @marvinm2 create subfolders to sort the [example queries](https://github.com/wikipathways/SPARQLQueries), however the folder only expands when you click on the folder icon. Could you also implement unfolding when clicking on the title next to the folder? Would be more user friendly I believe :)

**Comment by ammar257ammar** [comment]
Hi @DeniseSl22 ,

Issue should be fixed now. 

Please let me know if you encountered other issues.

Thanks

**Comment by DeniseSl22** [comment]
Hi Ammar, just checked but for me, clicking on the titles of the folders doesn't make them unfold. Maybe we can together check during our meeting tomorrow (so you see what I mean on my screen).

**Comment by DeniseSl22** [comment]
After new release of SNORQL interface, issue is fixed indeed!
