### ISSUE TITLE
Add runtime for results

### ISSUE THREAD

**Issue by DeniseSl22** [ammar257ammar/snorql-extended#10]
The Wikidata SPARQL endpoint nicely shows how long a query to took run; could that feature also be added to the WP SNORQL interface :smile: ? @ammar257ammar 

![image](https://user-images.githubusercontent.com/26277832/200579321-f702d508-fa59-4431-938a-91ff03df1aea.png)

**Comment by ammar257ammar** [comment]
Done, thanks for the suggestion :)
