### ISSUE TITLE
Fullscreen mode doesn't render after ~49 lines

### ISSUE THREAD

**Issue by DeniseSl22** [ammar257ammar/snorql-extended#11]
@ammar257ammar  I'm missing the last part of my query in the fullscreen mode, when it goes over ~49 lines, e.g.

![image](https://user-images.githubusercontent.com/26277832/200610816-af8c580e-23d8-44be-acee-880176291dca.png)

**Comment by ammar257ammar** [comment]
Done, thanks for the suggestion :)
