### ISSUE TITLE
Show # results

### ISSUE THREAD

**Issue by DeniseSl22** [ammar257ammar/snorql-extended#3]
Hi @ammar257ammar ; after executing a query, it would be nice to know how many results I have in total (amount of rows I think would be preferred), just to quickly check when I'm working on queries that my results are changing.

**Comment by egonw** [comment]
Seconded.

**Comment by ammar257ammar** [comment]
Thanks for the constructive feedback ^_^
This feature is now added to Snorql.

I will close this issue.
